[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "qemu-system-x86_64 -bios /usr/share/ovmf/x64/OVMF.4m.fd -net none"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"